import oracledb


def get_connection():
    return oracledb.connect(
        user = "C##POLAD",
        password = "polad55",
        dsn = "localhost:1521/xe"
    )


def create_tables():
    conn = get_connection()
    cursor = conn.cursor()

    cursor.execute(""" 
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE authors(
            id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR2(100),
            PRIMARY KEY (id)
        )'; 
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
 """)
    

    cursor.execute(""" 
    BEGIN
        EXECUTE IMMEDIATE 'CREATE  TABLE books(
            id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            book_name VARCHAR2(100),
            author_id NUMBER
        )';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;  
 """)
    
    conn.commit()
    cursor.close()
    conn.close()
    print("Cədvəllər yaradıldı (və ya artıq mövcuddur).")